**Exercício Medidas de Dispersão**

Utilizando média e medidas de dispersão, faça o seguinte para a base de nascidos vivos de SE em 2017:

1 - Compare as idades das mães que fizeram cesárea e das mães que fizeram parto normal

2 - Compare o peso da criança ao nascer das mães que fizeram cesárea e das mães que fizeram parto normal

3 - Compare o peso da criança ao nascer para as diferentes categorias de consultas pré-natal

4 - Compare quantidade de filhos vivos e mortos em relação ao tipo de gravidez (única, dupla, tripla ou mais)

5 - Compare a quantidade total de gravidezes (filhos vivos + filhos mortos) em relação a escolaridade

In [1]:
#Lendo Arquivo com Pandas
import pandas as pd

#Lendo o arquivo
pathArq = '/content/DNSE2017.csv'
sinasc = pd.read_csv(pathArq,dtype=str) #Colocando tudo como qualitativo
sinasc

      contador ORIGEM CODESTAB  ... TPROBSON PARIDADE KOTELCHUCK
0            1      1  2415631  ...       05        1          9
1            2      1  2005050  ...       03        1          3
2            3      1  2005050  ...       11        0          5
3            4      1  2005026  ...       05        1          2
4            5      1  2722429  ...       03        1          2
...        ...    ...      ...  ...      ...      ...        ...
33862    33863      1  2115891  ...       10        1          5
33863    33864      1  3137163  ...       02        0          3
33864    33865      1  2755092  ...       04        1          5
33865    33866      1  2077574  ...       04        1          5
33866    33867      2  6901743  ...       03        1          5

[33867 rows x 61 columns]

In [27]:
#Convertendo os tipos de dados
sinasc.QTDPARTNOR = pd.to_numeric(sinasc.QTDPARTNOR).astype(pd.Int64Dtype())
sinasc.QTDPARTCES = pd.to_numeric(sinasc.QTDPARTCES).astype(pd.Int64Dtype())
sinasc.IDADEMAE = pd.to_numeric(sinasc.IDADEMAE).astype(pd.Int64Dtype())
sinasc.PESO = pd.to_numeric(sinasc.PESO)
sinasc.QTDFILVIVO = pd.to_numeric(sinasc.QTDFILVIVO).astype(pd.Int64Dtype())
sinasc.QTDFILMORT = pd.to_numeric(sinasc.QTDFILMORT).astype(pd.Int64Dtype())

In [17]:
#Criando DataSets por tipo de parto
sinascNO = sinasc[sinasc.PARTO =='1'] #fazendo o filtro parto normal
sinascCE = sinasc[sinasc.PARTO =='2'] #fazendo o filtro parto cesária

**1 - Compare as idades das mães que fizeram cesárea e das mães que fizeram parto normal**

In [18]:
#Fazer a média do parto normal
mediaNormal = sinascNO.IDADEMAE.mean()
mediaCesaria = sinascCE.IDADEMAE.mean()

print ('Média Idade Parto Normal: ',mediaNormal, ' / Média Idade Parto Cesária: ',mediaCesaria)
print('\n ####################################################################################################################\n')
#Desvio Padrão da Idade das mães que fizeram parto normal e cesária
dsvPadraoNO = sinascNO.IDADEMAE.std()
dsvPadraoCE = sinascCE.IDADEMAE.std()

print ('Desvio Padrão Parto Normal: ',dsvPadraoNO, ' / Desvio Padrão Parto Cesária: ',dsvPadraoCE)

print('\n #################################################################################################################### \n')
#Intervalo Inter-quartil da Idade das mães que fizeram parto normal e cesária

InterQtrNO = sinascNO.IDADEMAE.quantile([0.25,0.75]).values
calcInterquartNo = InterQtrNO[1]-InterQtrNO[0]
print('Intervalo Interquartil Parto Normal: ',calcInterquartNo)

InterQtrCE = sinascCE.IDADEMAE.quantile([0.25,0.75]).values
calcInterquartCE = InterQtrCE[1]-InterQtrCE[0]
print('Intervalo Interquartil Parto Cesária: ',calcInterquartCE)

print('\n ####################################################################################################################\n')
#coeficiente de variacao da Idade das mães que fizeram parto normal e cesária
coefVarNo = ((dsvPadraoNO/mediaNormal)*100)
coefVarCE = ((dsvPadraoCE/mediaCesaria)*100)

print('Coeficiente Variacao Normal: ',coefVarNo, ' / Coeficiente Variacao Cesária: ',coefVarCE)

Média Idade Parto Normal:  24.98357030015798  / Média Idade Parto Cesária:  27.634743425919698

 ####################################################################################################################

Desvio Padrão Parto Normal:  6.713123832743319  / Desvio Padrão Parto Cesária:  6.732200555321283

 ####################################################################################################################

Intervalo Interquartil Parto Normal:  10.0
Intervalo Interquartil Parto Cesária:  11.0

 ####################################################################################################################

Coeficiente Variacao Normal:  26.870154073618814  / Coeficiente Variacao Cesária:  24.361364430135765

**2 - Compare o peso da criança ao nascer das mães que fizeram cesárea e das mães que fizeram parto normal**

In [22]:
#Fazer a média do Peso das Criancas que nasceram de parto cesária e de parto normal
mediaPesoNormal = sinascNO.PESO.mean()
mediaPesoCesaria = sinascCE.PESO.mean()

print ('Média Peso Crianca Parto Normal: ',mediaPesoNormal, ' / Média Peso Crianca Parto Cesária: ',mediaPesoCesaria)
print('\n ####################################################################################################################\n')

#Desvio Padrão do peso das Criancas que naceram de parto normal e cesária
dsvPadraoPesoNO = sinascNO.PESO.std()
dsvPadraoPesoCE = sinascCE.PESO.std()

print ('Desvio Padrão Parto Normal: ',dsvPadraoPesoNO, ' / Desvio Padrão Parto Cesária: ',dsvPadraoPesoCE)

print('\n #################################################################################################################### \n')

#Intervalo Inter-quartil do peso das Criancas que naceram de parto normal e cesária

InterQtrPesoNO = sinascNO.PESO.quantile([0.25,0.75]).values
calcInterquartPesoNo = InterQtrPesoNO[1]-InterQtrPesoNO[0]
print('Intervalo Interquartil Parto Normal: ',calcInterquartPesoNo)

InterQtrPesoCE = sinascCE.PESO.quantile([0.25,0.75]).values
calcInterquartPesoCE = InterQtrPesoCE[1]-InterQtrPesoCE[0]
print('Intervalo Interquartil Parto Cesária: ',calcInterquartPesoCE)

print('\n ####################################################################################################################\n')
#coeficiente de variacao do peso das Criancas que naceram de parto normal e cesária
coefVarPesoNo = ((dsvPadraoPesoNO/mediaPesoNormal)*100)
coefVarPesoCE = ((dsvPadraoPesoCE/mediaPesoCesaria)*100)

print('Coeficiente Variacao Normal: ',coefVarNo, ' / Coeficiente Variacao Cesária: ',coefVarCE)

Média Peso Crianca Parto Normal:  3192.6047932578354  / Média Peso Crianca Parto Cesária:  3262.2962539511736

 ####################################################################################################################

Desvio Padrão Parto Normal:  555.2919465469533  / Desvio Padrão Parto Cesária:  598.5973542998237

 ####################################################################################################################

Intervalo Interquartil Parto Normal:  610.0
Intervalo Interquartil Parto Cesária:  678.0

 ####################################################################################################################

Coeficiente Variacao Normal:  26.870154073618814  / Coeficiente Variacao Cesária:  24.361364430135765

**3 - Compare o peso da criança ao nascer para as diferentes categorias de consultas pré-natal**

In [23]:
#Criando DataSets por categorias de Pré Natal
sinascPN1 = sinasc[sinasc.CONSULTAS =='1'] # Menos de 1 Consulta Pré Natal
sinascPN2 = sinasc[sinasc.CONSULTAS =='2'] # De 1 a 3 Consutas Pré Natal
sinascPN3 = sinasc[sinasc.CONSULTAS =='3'] # De 4 a 6 Consultas Pré Natal
sinascPN4 = sinasc[sinasc.CONSULTAS =='4'] # 7 ou mais Consultas Pré Natal

In [26]:
#Média do peso das Criancas para as diferentes categorias de Pré Natal
mediaPesoPN1 = sinascPN1.PESO.mean()
mediaPesoPN2 = sinascPN2.PESO.mean()
mediaPesoPN3 = sinascPN3.PESO.mean()
mediaPesoPN4 = sinascPN4.PESO.mean()

print ('Média Peso Pré Natal 1: ',mediaPesoPN1)
print ('Média Peso Pré Natal 2: ',mediaPesoPN2)
print ('Média Peso Pré Natal 3: ',mediaPesoPN3)
print ('Média Peso Pré Natal 4: ',mediaPesoPN4)
print('\n ####################################################################################################################\n')

#Desvio Padrão do peso das Criancas para as diferentes categorias de Pré Natal
dsvPadraoPN1 = sinascPN1.PESO.std()
dsvPadraoPN2 = sinascPN2.PESO.std()
dsvPadraoPN3 = sinascPN3.PESO.std()
dsvPadraoPN4 = sinascPN4.PESO.std()

print ('Desvio Padrão do Peso Pré Natal 1: ',dsvPadraoPN1)
print ('Desvio Padrão do Peso Pré Natal 2: ',dsvPadraoPN2)
print ('Desvio Padrão do Peso Pré Natal 3: ',dsvPadraoPN3)
print ('Desvio Padrão do Peso Pré Natal 4: ',dsvPadraoPN4)

print('\n #################################################################################################################### \n')

#Intervalo Inter-quartil do peso das Criancas que naceram de parto normal e cesária

InterQtrPesoPN1 = sinascPN1.PESO.quantile([0.25,0.75]).values
calcItrQrtPesoPN1 = InterQtrPesoPN1[1]-InterQtrPesoPN1[0]
print('Intervalo Interquartil Pré Natal 1: ',calcItrQrtPesoPN1)

InterQtrPesoPN2 = sinascPN2.PESO.quantile([0.25,0.75]).values
calcItrQrtPesoPN2 = InterQtrPesoPN2[1]-InterQtrPesoPN2[0]
print('Intervalo Interquartil Pré Natal 2: ',calcItrQrtPesoPN2)

InterQtrPesoPN3 = sinascPN3.PESO.quantile([0.25,0.75]).values
calcItrQrtPesoPN3 = InterQtrPesoPN3[1]-InterQtrPesoPN3[0]
print('Intervalo Interquartil Pré Natal 3: ',calcItrQrtPesoPN3)

InterQtrPesoPN4 = sinascPN4.PESO.quantile([0.25,0.75]).values
calcItrQrtPesoPN4 = InterQtrPesoPN4[1]-InterQtrPesoPN4[0]
print('Intervalo Interquartil Pré Natal 4: ',calcItrQrtPesoPN4)

print('\n ####################################################################################################################\n')
#coeficiente de variacao do peso das Criancas que naceram de parto normal e cesária
coefVarPesoPN1 = ((dsvPadraoPN1/mediaPesoPN1)*100)
coefVarPesoPN2 = ((dsvPadraoPN2/mediaPesoPN2)*100)
coefVarPesoPN3 = ((dsvPadraoPN3/mediaPesoPN3)*100)
coefVarPesoPN4 = ((dsvPadraoPN4/mediaPesoPN4)*100)

print('Coeficiente Variacao Pré Natal 1: ',coefVarPesoPN1)
print('Coeficiente Variacao Pré Natal 2: ',coefVarPesoPN2)
print('Coeficiente Variacao Pré Natal 3: ',coefVarPesoPN3)
print('Coeficiente Variacao Pré Natal 4: ',coefVarPesoPN4)

Média Peso Pré Natal 1:  3085.7057142857143
Média Peso Pré Natal 2:  3022.836124401914
Média Peso Pré Natal 3:  3166.4481224417154
Média Peso Pré Natal 4:  3295.601250066211

 ####################################################################################################################

Desvio Padrão do Peso Pré Natal 1:  676.3215285616058
Desvio Padrão do Peso Pré Natal 2:  765.4774563785681
Desvio Padrão do Peso Pré Natal 3:  600.6850101167469
Desvio Padrão do Peso Pré Natal 4:  500.74534594318817

 ####################################################################################################################

Intervalo Interquartil Pré Natal 1:  718.0
Intervalo Interquartil Pré Natal 2:  737.0
Intervalo Interquartil Pré Natal 3:  670.0
Intervalo Interquartil Pré Natal 4:  610.0

 ####################################################################################################################

Coeficiente Variacao Pré Natal 1:  21.917888197519254
Coeficiente Variacao Pré Natal 2:  25.323154311913697
Coeficiente Variacao Pré Natal 3:  18.970309535769243
Coeficiente Variacao Pré Natal 4:  15.194354776177118

**4 - Compare quantidade de filhos vivos e mortos em relação ao tipo de gravidez (única, dupla, tripla ou mais)**

In [32]:
#Criando DataSets por tipo de Gravidez
sinascGra1 = sinasc[sinasc.GRAVIDEZ =='1'] # Única
sinascGra2 = sinasc[sinasc.GRAVIDEZ =='2'] # Dupla
sinascGra3 = sinasc[sinasc.GRAVIDEZ =='3'] # Tripla ou mais

In [34]:
#Média de Quantidade de Filhos Vivos / Mortos para cada tipo de gravidez
mediaVivoGra1 = sinascGra1.QTDFILVIVO.mean()
mediaMortGra1 = sinascGra1.QTDFILMORT.mean()

mediaVivoGra2 = sinascGra2.QTDFILVIVO.mean()
mediaMortGra2 = sinascGra2.QTDFILMORT.mean()

mediaVivoGra3 = sinascGra3.QTDFILVIVO.mean()
mediaMortGra3 = sinascGra3.QTDFILMORT.mean()

print ('Média Filhos Vivos Gravidez 1: ',mediaVivoGra1, ' / Média Filhos Mortos Gravidez 1: ',mediaMortGra1)
print ('Média Filhos Vivos Gravidez 2: ',mediaVivoGra2, ' / Média Filhos Mortos Gravidez 2: ',mediaMortGra2)
print ('Média Filhos Vivos Gravidez 3: ',mediaVivoGra3, ' / Média Filhos Mortos Gravidez 3: ',mediaMortGra3)

print('\n ####################################################################################################################\n')

#Desvio Padrão de Quantidade de Filhos Vivos / Mortos para cada tipo de gravidez
dsvPdrVivoGra1 = sinascGra1.QTDFILVIVO.std()
dsvPdrMortGra1 = sinascGra1.QTDFILMORT.std()

dsvPdrVivoGra2 = sinascGra2.QTDFILVIVO.std()
dsvPdrMortGra2 = sinascGra2.QTDFILMORT.std()

dsvPdrVivoGra3 = sinascGra3.QTDFILVIVO.std()
dsvPdrMortGra3 = sinascGra3.QTDFILMORT.std()

print ('Desvio Padrão Filhos Vivos Gravidez 1: ',dsvPdrVivoGra1)
print ('Desvio Padrão Filhos Mortos Gravidez 1: ',dsvPdrMortGra1)

print ('Desvio Padrão Filhos Vivos Gravidez 2: ',dsvPdrVivoGra2)
print ('Desvio Padrão Filhos Mortos Gravidez 2: ',dsvPdrMortGra2)

print ('Desvio Padrão Filhos Vivos Gravidez 3: ',dsvPdrVivoGra3)
print ('Desvio Padrão Filhos Mortos Gravidez 3: ',dsvPdrMortGra3)

print('\n #################################################################################################################### \n')

#Intervalo Inter-quartil de Quantidade de Filhos Vivos / Mortos para cada tipo de gravidez

InterQtrVivoGra1 = sinascGra1.QTDFILVIVO.quantile([0.25,0.75]).values
calcInterQtrVivoGra1 = InterQtrVivoGra1[1]-InterQtrVivoGra1[0]
print('Intervalo Interquartil Vivos Gravidez 1: ',calcInterQtrVivoGra1)

InterQtrMortGra1 = sinascGra1.QTDFILMORT.quantile([0.25,0.75]).values
calcInterQtrMortGra1 = InterQtrMortGra1[1]-InterQtrMortGra1[0]
print('Intervalo Interquartil Mortos Gravidez 1: ',calcInterQtrMortGra1)

InterQtrVivoGra2 = sinascGra2.QTDFILVIVO.quantile([0.25,0.75]).values
calcInterQtrVivoGra2 = InterQtrVivoGra2[1]-InterQtrVivoGra2[0]
print('Intervalo Interquartil Vivos Gravidez 2: ',calcInterQtrVivoGra1)

InterQtrMortGra2 = sinascGra2.QTDFILMORT.quantile([0.25,0.75]).values
calcInterQtrMortGra2 = InterQtrMortGra2[1]-InterQtrMortGra2[0]
print('Intervalo Interquartil Mortos Gravidez 2: ',calcInterQtrMortGra2)

InterQtrVivoGra3 = sinascGra3.QTDFILVIVO.quantile([0.25,0.75]).values
calcInterQtrVivoGra3 = InterQtrVivoGra3[1]-InterQtrVivoGra3[0]
print('Intervalo Interquartil Vivos Gravidez 3: ',InterQtrVivoGra3)

InterQtrMortGra3 = sinascGra3.QTDFILMORT.quantile([0.25,0.75]).values
calcInterQtrMortGra3 = InterQtrMortGra3[1]-InterQtrMortGra3[0]
print('Intervalo Interquartil Mortos Gravidez 3: ',calcInterQtrMortGra3)

print('\n ####################################################################################################################\n')
#coeficiente de variacao de Quantidade de Filhos Vivos / Mortos para cada tipo de gravidez
coefVarVivoGra1 = ((dsvPdrVivoGra1/mediaVivoGra1)*100)
coefVarMortGra1 = ((dsvPdrMortGra1/mediaMortGra1)*100)

coefVarVivoGra2 = ((dsvPdrVivoGra2/mediaVivoGra2)*100)
coefVarMortGra2 = ((dsvPdrMortGra2/mediaMortGra2)*100)

coefVarVivoGra3 = ((dsvPdrVivoGra3/mediaVivoGra3)*100)
coefVarMortGra3 = ((dsvPdrMortGra3/mediaMortGra3)*100)


print('Coeficiente Variacao Filhos Vivos Gravidez 1: ',coefVarVivoGra1,'Coeficiente Variacao Filhos Vivos Gravidez 1: ',coefVarMortGra1)
print('Coeficiente Variacao Filhos Vivos Gravidez 2: ',coefVarVivoGra2,'Coeficiente Variacao Filhos Vivos Gravidez 2: ',coefVarMortGra2)
print('Coeficiente Variacao Filhos Vivos Gravidez 3: ',coefVarVivoGra3,'Coeficiente Variacao Filhos Vivos Gravidez 3: ',coefVarMortGra3)

Média Filhos Vivos Gravidez 1:  1.121665538253216  / Média Filhos Mortos Gravidez 1:  0.3096697499907129
Média Filhos Vivos Gravidez 2:  1.197749196141479  / Média Filhos Mortos Gravidez 2:  0.3501683501683502
Média Filhos Vivos Gravidez 3:  0.8333333333333334  / Média Filhos Mortos Gravidez 3:  0.2222222222222222

 ####################################################################################################################

Desvio Padrão Filhos Vivos Gravidez 1:  1.4171397660335923
Desvio Padrão Filhos Mortos Gravidez 1:  0.6470136626816787
Desvio Padrão Filhos Vivos Gravidez 2:  1.4077522020149482
Desvio Padrão Filhos Mortos Gravidez 2:  0.6533929904283866
Desvio Padrão Filhos Vivos Gravidez 3:  1.9174124721184262
Desvio Padrão Filhos Mortos Gravidez 3:  0.42779263194649864

 ####################################################################################################################

Intervalo Interquartil Vivos Gravidez 1:  2.0
Intervalo Interquartil Mortos Gravidez 1:  0.0
Intervalo Interquartil Vivos Gravidez 2:  2.0
Intervalo Interquartil Mortos Gravidez 2:  1.0
Intervalo Interquartil Vivos Gravidez 3:  [0.0 0.0]
Intervalo Interquartil Mortos Gravidez 3:  0.0

 ####################################################################################################################

Coeficiente Variacao Filhos Vivos Gravidez 1:  126.34245394046091 Coeficiente Variacao Filhos Vivos Gravidez 1:  208.93666969443507
Coeficiente Variacao Filhos Vivos Gravidez 2:  117.53313686621448 Coeficiente Variacao Filhos Vivos Gravidez 2:  186.5939597665681
Coeficiente Variacao Filhos Vivos Gravidez 3:  230.08949665421113 Coeficiente Variacao Filhos Vivos Gravidez 3:  192.5066843759244

**5 - Compare a quantidade total de gravidezes (filhos vivos + filhos mortos) em relação a escolaridade**

In [60]:
#Criando DataSets em Relacao a Escolaridade


sinascEsc1 = sinasc[sinasc.ESCMAE =='1'] # Única
sinascTotGraEsc1 = sinascEsc1.QTDFILVIVO+sinascEsc1.QTDFILMORT

sinascEsc2 = sinasc[sinasc.ESCMAE =='2'] # Única
sinascTotGraEsc2 = sinascEsc2.QTDFILVIVO+sinascEsc2.QTDFILMORT

sinascEsc3 = sinasc[sinasc.ESCMAE =='3'] # Única
sinascTotGraEsc3 = sinascEsc1.QTDFILVIVO+sinascEsc1.QTDFILMORT

sinascEsc4 = sinasc[sinasc.ESCMAE =='4'] # Única
sinascTotGraEsc4 = sinascEsc2.QTDFILVIVO+sinascEsc2.QTDFILMORT

sinascEsc5 = sinasc[sinasc.ESCMAE =='5'] # Única
sinascTotGraEsc5 = sinascEsc1.QTDFILVIVO+sinascEsc1.QTDFILMORT

Intervalo Interquartil do total de Gravidezes para Escolaridade 1:  4.0

In [61]:
#Média do Total de Gravidezes em relacao a Escolaridade
mediaGraEsc1 = sinascTotGraEsc1.mean()
mediaGraEsc2 = sinascTotGraEsc2.mean()
mediaGraEsc3 = sinascTotGraEsc3.mean()
mediaGraEsc4 = sinascTotGraEsc4.mean()
mediaGraEsc5 = sinascTotGraEsc5.mean()


print ('Média do Total de Gravidezes para Escolaridade 1: ',mediaGraEsc1)
print ('Média do Total de Gravidezes para Escolaridade 2: ',mediaGraEsc2)
print ('Média do Total de Gravidezes para Escolaridade 3: ',mediaGraEsc3)
print ('Média do Total de Gravidezes para Escolaridade 4: ',mediaGraEsc4)
print ('Média do Total de Gravidezes para Escolaridade 5: ',mediaGraEsc5)

print('\n ####################################################################################################################\n')

#Desvio Padrão do total de Gravidezes em relação a Escolaridade
dsvPdrTotGraEsc1 = sinascTotGraEsc1.std()
dsvPdrTotGraEsc2 = sinascTotGraEsc2.std()
dsvPdrTotGraEsc3 = sinascTotGraEsc3.std()
dsvPdrTotGraEsc4 = sinascTotGraEsc4.std()
dsvPdrTotGraEsc5 = sinascTotGraEsc5.std()

print ('Desvio Padrão do Total de Gravidezes para Escolaridade 1: ',dsvPdrTotGraEsc1)
print ('Desvio Padrão do Total de Gravidezes para Escolaridade 2: ',dsvPdrTotGraEsc2)
print ('Desvio Padrão do Total de Gravidezes para Escolaridade 3: ',dsvPdrTotGraEsc3)
print ('Desvio Padrão do Total de Gravidezes para Escolaridade 4: ',dsvPdrTotGraEsc4)
print ('Desvio Padrão do Total de Gravidezes para Escolaridade 5: ',dsvPdrTotGraEsc5)


print('\n #################################################################################################################### \n')

#Intervalo Inter-quartil do total de Gravidezes em relação a Escolaridade

ItrQrtTotGraEsc1 = sinascTotGraEsc1.quantile([0.25,0.75]).values
calcItrQrtTotGraEsc1 = ItrQrtTotGraEsc1[1]-ItrQrtTotGraEsc1[0]
print('Intervalo Interquartil do total de Gravidezes para Escolaridade 1: ',calcItrQrtTotGraEsc1)

ItrQrtTotGraEsc2 = sinascTotGraEsc2.quantile([0.25,0.75]).values
calcItrQrtTotGraEsc2 = ItrQrtTotGraEsc2[1]-ItrQrtTotGraEsc2[0]
print('Intervalo Interquartil do total de Gravidezes para Escolaridade 2: ',calcItrQrtTotGraEsc2)

ItrQrtTotGraEsc3 = sinascTotGraEsc2.quantile([0.25,0.75]).values
calcItrQrtTotGraEsc3 = ItrQrtTotGraEsc3[1]-ItrQrtTotGraEsc3[0]
print('Intervalo Interquartil do total de Gravidezes para Escolaridade 3: ',calcItrQrtTotGraEsc3)

ItrQrtTotGraEsc4 = sinascTotGraEsc2.quantile([0.25,0.75]).values
calcItrQrtTotGraEsc4 = ItrQrtTotGraEsc4[1]-ItrQrtTotGraEsc4[0]
print('Intervalo Interquartil do total de Gravidezes para Escolaridade 4: ',calcItrQrtTotGraEsc4)


ItrQrtTotGraEsc5 = sinascTotGraEsc2.quantile([0.25,0.75]).values
calcItrQrtTotGraEsc5 = ItrQrtTotGraEsc5[1]-ItrQrtTotGraEsc5[0]
print('Intervalo Interquartil do total de Gravidezes para Escolaridade 5: ',calcItrQrtTotGraEsc5)


print('\n ####################################################################################################################\n')
#coeficiente de variacao do peso das Criancas que naceram de parto normal e cesária
coefVarTotGraEsc1 = ((dsvPdrTotGraEsc1/mediaGraEsc1)*100)
coefVarTotGraEsc2 = ((dsvPdrTotGraEsc2/mediaGraEsc2)*100)
coefVarTotGraEsc3 = ((dsvPdrTotGraEsc3/mediaGraEsc3)*100)
coefVarTotGraEsc4 = ((dsvPdrTotGraEsc4/mediaGraEsc4)*100)
coefVarTotGraEsc5 = ((dsvPdrTotGraEsc5/mediaGraEsc5)*100)

print('Coeficiente Variacao do Total de Gravidezes para Escolaridade 1: ',coefVarTotGraEsc1)
print('Coeficiente Variacao do Total de Gravidezes para Escolaridade 2: ',coefVarTotGraEsc2)
print('Coeficiente Variacao do Total de Gravidezes para Escolaridade 3: ',coefVarTotGraEsc3)
print('Coeficiente Variacao do Total de Gravidezes para Escolaridade 4: ',coefVarTotGraEsc4)

Média do Total de Gravidezes para Escolaridade 1:  5.3105590062111805
Média do Total de Gravidezes para Escolaridade 2:  3.5444630872483223
Média do Total de Gravidezes para Escolaridade 3:  5.3105590062111805
Média do Total de Gravidezes para Escolaridade 4:  3.5444630872483223
Média do Total de Gravidezes para Escolaridade 5:  5.3105590062111805

 ####################################################################################################################

Desvio Padrão do Total de Gravidezes para Escolaridade 1:  3.1349561895757025
Desvio Padrão do Total de Gravidezes para Escolaridade 2:  2.7203316734203207
Desvio Padrão do Total de Gravidezes para Escolaridade 3:  3.1349561895757025
Desvio Padrão do Total de Gravidezes para Escolaridade 4:  2.7203316734203207
Desvio Padrão do Total de Gravidezes para Escolaridade 5:  3.1349561895757025

 ####################################################################################################################

Intervalo Interquartil do total de Gravidezes para Escolaridade 1:  4.0
Intervalo Interquartil do total de Gravidezes para Escolaridade 2:  3.0
Intervalo Interquartil do total de Gravidezes para Escolaridade 3:  3.0
Intervalo Interquartil do total de Gravidezes para Escolaridade 4:  3.0
Intervalo Interquartil do total de Gravidezes para Escolaridade 5:  3.0

 ####################################################################################################################

Coeficiente Variacao do Total de Gravidezes para Escolaridade 1:  59.03250836510971
Coeficiente Variacao do Total de Gravidezes para Escolaridade 2:  76.74876579211886
Coeficiente Variacao do Total de Gravidezes para Escolaridade 3:  59.03250836510971
Coeficiente Variacao do Total de Gravidezes para Escolaridade 4:  76.74876579211886